import { CleaningRequestStatus, Prisma } from "../generated/prisma/client";
import { getCleaningRequestWorkflowReadiness } from "../lib/cleaning-request-workflow";
import { CleaningRequestWorkflowInputSchema } from "../lib/validations/cleaning-request-workflow.schema";
import { transitionCleaningRequestStatusInTransaction, type LifecycleTransaction } from "./cleaning-request-lifecycle.service";

type CurrentRequest = { id: string; requestNumber: string; status: CleaningRequestStatus; confirmedPrice: Prisma.Decimal | null; scheduledStart: Date | null; scheduledEnd: Date | null; assignments: Array<{ id: string }> };
type WorkflowTransaction = Omit<LifecycleTransaction, "cleaningRequest"> & { cleaningRequest: { findUnique: (args: Record<string, unknown>) => Promise<CurrentRequest | null>; updateMany: LifecycleTransaction["cleaningRequest"]["updateMany"] } };
type Database = { $transaction: <T>(callback: (transaction: WorkflowTransaction) => Promise<T>) => Promise<T> };
export type CleaningRequestWorkflowResult = { success: true; request: { id: string; requestNumber: string; status: CleaningRequestStatus }; transition: { id: string; fromStatus: CleaningRequestStatus; toStatus: CleaningRequestStatus; reason: string | null; createdAt: string } } | { success: false; reason: "INVALID_INPUT" | "REQUEST_NOT_FOUND" | "INVALID_REQUEST_STATUS" | "NO_ASSIGNED_WORKERS" | "REQUEST_NOT_OPERATIONALLY_READY" | "STATUS_CONFLICT" | "INTERNAL_ERROR" };

async function transition(adminId: string, input: unknown, fromStatus: CleaningRequestStatus, toStatus: CleaningRequestStatus, options: { database?: Database; now?: Date } = {}): Promise<CleaningRequestWorkflowResult> {
  const parsed = CleaningRequestWorkflowInputSchema.safeParse(input); if (!parsed.success) return { success: false, reason: "INVALID_INPUT" }; const database = options.database ?? (await import("../lib/db/prisma")).prisma as unknown as Database; const now = options.now ?? new Date();
  try { return await database.$transaction(async (transaction) => { const current = await transaction.cleaningRequest.findUnique({ where: { id: parsed.data.cleaningRequestId }, select: { id: true, requestNumber: true, status: true, confirmedPrice: true, scheduledStart: true, scheduledEnd: true, assignments: { select: { id: true } } } }); if (!current) return { success: false, reason: "REQUEST_NOT_FOUND" }; if (current.status !== fromStatus) return { success: false, reason: "INVALID_REQUEST_STATUS" }; const readiness = getCleaningRequestWorkflowReadiness({ ...current, assignmentCount: current.assignments.length }); if (fromStatus === CleaningRequestStatus.ASSIGNED && readiness.startBlockingReasons.includes("NO_ASSIGNED_WORKERS")) return { success: false, reason: "NO_ASSIGNED_WORKERS" }; if (fromStatus === CleaningRequestStatus.ASSIGNED && readiness.startBlockingReasons.some((reason) => reason !== "NO_ASSIGNED_WORKERS")) return { success: false, reason: "REQUEST_NOT_OPERATIONALLY_READY" }; if (fromStatus === CleaningRequestStatus.IN_PROGRESS && readiness.completeBlockingReasons.includes("NO_ASSIGNED_WORKERS")) return { success: false, reason: "NO_ASSIGNED_WORKERS" }; const result = await transitionCleaningRequestStatusInTransaction(adminId, transaction as unknown as LifecycleTransaction, current, toStatus, null, now); if (result.success) return result; return result.reason === "STATUS_CONFLICT" ? { success: false, reason: "STATUS_CONFLICT" as const } : { success: false, reason: "INTERNAL_ERROR" as const }; }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError) return { success: false, reason: "INTERNAL_ERROR" }; return { success: false, reason: "INTERNAL_ERROR" }; }
}
export function startCleaningForAdmin(adminId: string, input: unknown, options: { database?: Database; now?: Date } = {}) { return transition(adminId, input, CleaningRequestStatus.ASSIGNED, CleaningRequestStatus.IN_PROGRESS, options); }
export function completeCleaningForAdmin(adminId: string, input: unknown, options: { database?: Database; now?: Date } = {}) { return transition(adminId, input, CleaningRequestStatus.IN_PROGRESS, CleaningRequestStatus.COMPLETED, options); }
