import { Prisma, type WorkerType } from "../generated/prisma/client";
import { WorkerCreationInputSchema, WorkerActiveStateInputSchema } from "../lib/validations/worker.schema";
import { normalizePhone } from "./cleaning-request-validation.service";

type Database = { worker: { findMany: (args: Record<string, unknown>) => Promise<Array<{ id: string; firstName: string; lastName: string; phone: string | null; email: string | null }>>; create: (args: Record<string, unknown>) => Promise<{ id: string; firstName: string; lastName: string; phone: string | null; email: string | null; type: WorkerType; isActive: boolean }>; findUnique: (args: Record<string, unknown>) => Promise<{ id: string; firstName: string; lastName: string; isActive: boolean } | null>; updateMany: (args: Record<string, unknown>) => Promise<{ count: number }> } };
function fieldErrors(error: { issues: Array<{ path: PropertyKey[]; message: string }> }) { return error.issues.reduce<Record<string, string[]>>((out, issue) => { const key = String(issue.path[0] ?? "form"); out[key] = [...(out[key] ?? []), issue.message]; return out; }, {}); }
export type WorkerCreationResult = { status: "SUCCESS"; worker: { id: string; firstName: string; lastName: string; phone: string | null; email: string | null; type: WorkerType; isActive: boolean } } | { status: "INVALID_INPUT"; fieldErrors: Record<string, string[]> } | { status: "POSSIBLE_DUPLICATE"; matches: Array<{ id: string; firstName: string; lastName: string; phone: string | null; email: string | null }> } | { status: "INTERNAL_ERROR" };
export type WorkerActiveStateResult = { status: "SUCCESS"; worker: { id: string; isActive: boolean } } | { status: "INVALID_INPUT" | "WORKER_NOT_FOUND" | "NO_STATE_CHANGE" | "WORKER_CONFLICT" | "INTERNAL_ERROR" };

export async function createWorkerForAdmin(input: unknown, options: { database?: Database } = {}): Promise<WorkerCreationResult> {
  const parsed = WorkerCreationInputSchema.safeParse(input); if (!parsed.success) return { status: "INVALID_INPUT", fieldErrors: fieldErrors(parsed.error) }; const phone = parsed.data.phone ? normalizePhone(parsed.data.phone) : null; if (parsed.data.phone && !phone) return { status: "INVALID_INPUT", fieldErrors: { phone: ["Enter a valid US phone number."] } }; const database = options.database ?? (await import("../lib/db/prisma")).prisma as unknown as Database;
  try { const matches = await database.worker.findMany({ where: { OR: [{ email: parsed.data.email ?? undefined }, { phone: phone ?? undefined }], NOT: [{ email: null, phone: null }] }, select: { id: true, firstName: true, lastName: true, phone: true, email: true } }); if (matches.length && !parsed.data.allowDuplicateContact) return { status: "POSSIBLE_DUPLICATE", matches }; const worker = await database.worker.create({ data: { firstName: parsed.data.firstName, lastName: parsed.data.lastName, phone, email: parsed.data.email, type: parsed.data.type, isActive: true }, select: { id: true, firstName: true, lastName: true, phone: true, email: true, type: true, isActive: true } }); return { status: "SUCCESS", worker }; } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError) return { status: "INTERNAL_ERROR" }; return { status: "INTERNAL_ERROR" }; }
}

export async function setWorkerActiveStateForAdmin(input: unknown, options: { database?: Database } = {}): Promise<WorkerActiveStateResult> {
  const parsed = WorkerActiveStateInputSchema.safeParse(input); if (!parsed.success) return { status: "INVALID_INPUT" }; const database = options.database ?? (await import("../lib/db/prisma")).prisma as unknown as Database;
  try { const current = await database.worker.findUnique({ where: { id: parsed.data.workerId }, select: { id: true, firstName: true, lastName: true, isActive: true } }); if (!current) return { status: "WORKER_NOT_FOUND" }; if (current.isActive === parsed.data.isActive) return { status: "NO_STATE_CHANGE" }; const updated = await database.worker.updateMany({ where: { id: current.id, isActive: current.isActive }, data: { isActive: parsed.data.isActive } }); if (updated.count !== 1) return { status: "WORKER_CONFLICT" }; return { status: "SUCCESS", worker: { id: current.id, isActive: parsed.data.isActive } }; } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError) return { status: "INTERNAL_ERROR" }; return { status: "INTERNAL_ERROR" }; }
}
