"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { createWorkerAction } from "@/app/actions/create-worker";

export default function WorkerForm() { const router = useRouter(); const [form, setForm] = useState({ firstName: "", lastName: "", phone: "", email: "", type: "CREW" }); const [duplicate, setDuplicate] = useState(false); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition(); const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value })); const submit = (event: React.FormEvent) => { event.preventDefault(); setError(null); startTransition(async () => { const result = await createWorkerAction({ ...form, allowDuplicateContact: duplicate }); if (result.status === "SUCCESS") router.push(`/admin/workers/${result.worker.id}?created=1`); else if (result.status === "POSSIBLE_DUPLICATE") setDuplicate(true); else if (result.status === "INVALID_INPUT") setError(Object.values(result.fieldErrors).flat()[0] ?? "Check the form and try again."); else setError("We could not save this worker. Try again."); }); };
  return <form onSubmit={submit} className="space-y-6">{error ? <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900">{error}</div> : null}{duplicate ? <div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><p className="font-semibold">A worker with this contact information may already exist.</p><p className="mt-1">Review the directory before deliberately creating a duplicate.</p><button type="submit" className="mt-4 min-h-10 rounded-lg bg-amber-700 px-4 font-semibold text-white">Create anyway</button></div> : null}<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-semibold text-slate-950">Worker profile</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">First name<input required value={form.firstName} onChange={(e) => update("firstName", e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal" /></label><label className="text-sm font-semibold text-slate-700">Last name<input required value={form.lastName} onChange={(e) => update("lastName", e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal" /></label><label className="text-sm font-semibold text-slate-700">Phone<input value={form.phone} onChange={(e) => update("phone", e.target.value)} placeholder="(973) 555-1234" className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal" /></label><label className="text-sm font-semibold text-slate-700">Email<input type="email" value={form.email} onChange={(e) => update("email", e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal" /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Worker type<select value={form.type} onChange={(e) => update("type", e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal"><option value="CREW">Crew</option><option value="CONTRACTOR">Contractor</option></select></label></div><p className="mt-3 text-sm text-slate-500">At least a phone number or email address is required. New workers are active by default.</p></section><div className="flex flex-wrap gap-3"><button disabled={pending} className="min-h-11 rounded-xl bg-blue-700 px-5 font-semibold text-white disabled:bg-slate-300">{pending ? "Saving…" : duplicate ? "Create anyway" : "Add worker"}</button><Link href="/admin/workers" className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 px-5 font-semibold text-slate-700">Cancel</Link></div></form>;
}
