import assert from "node:assert/strict";
import test from "node:test";
import { CleaningEstimateOutcome, CleaningRequestStatus, Prisma, PropertyType } from "../../generated/prisma/client.js";
import { getAdminCustomerDetail } from "../admin-customer-detail.service.js";

function row() { return { id: "customer-1", name: "Jane Smith", email: "jane@example.com", phone: "+19735551234", isActive: true, createdAt: new Date("2026-08-01T00:00:00Z"), updatedAt: new Date("2026-08-02T00:00:00Z"), properties: [{ id: "inactive", label: null, addressLine1: "2 Main", addressLine2: null, city: "Newark", state: "NJ", postalCode: "07102", propertyType: PropertyType.HOUSE, bedrooms: null, bathrooms: new Prisma.Decimal("1.5"), approximateSquareFeet: null, isActive: false, createdAt: new Date("2026-08-02"), updatedAt: new Date("2026-08-02") }, { id: "active", label: "Home", addressLine1: "1 Main", addressLine2: null, city: "Newark", state: "NJ", postalCode: "07101", propertyType: PropertyType.HOUSE, bedrooms: 2, bathrooms: null, approximateSquareFeet: 1200, isActive: true, createdAt: new Date("2026-08-03"), updatedAt: new Date("2026-08-03") }], requests: [{ id: "request-1", requestNumber: "JC-2026-0001", status: CleaningRequestStatus.CONFIRMED, propertyType: PropertyType.HOUSE, preferredDate: new Date("2026-08-21"), preferredTimeWindow: "MORNING", scheduledStart: new Date("2026-08-21T17:00:00Z"), estimateOutcome: CleaningEstimateOutcome.AUTOMATIC_ESTIMATE, estimatedPrice: new Prisma.Decimal("200"), confirmedPrice: new Prisma.Decimal("250"), createdAt: new Date("2026-08-04"), service: { name: "Deep Cleaning" } }] }; }
function database(value: ReturnType<typeof row> | null) { return { customer: { async findUnique() { return value; } } }; }

test("serializes current profile, properties, and explicitly linked request history", async () => { const result = await getAdminCustomerDetail("customer-1", { database: database(row()) as never }); assert.equal(result?.properties[0]?.id, "inactive"); assert.equal(result?.properties[0]?.bathrooms, "1.5"); assert.equal(result?.requests[0]?.estimatedPrice, "200.00"); assert.equal(result?.requests[0]?.confirmedPrice, "250.00"); assert.equal(result?.requests[0]?.scheduledStart, "2026-08-21T17:00:00.000Z"); assert.equal(result?.requests[0]?.serviceName, "Deep Cleaning"); });
test("returns null for unknown customer", async () => { assert.equal(await getAdminCustomerDetail("missing", { database: database(null) as never }), null); });
