/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { CleaningRequestStatus } from "../../generated/prisma/client";
import { assignWorkerToCleaningRequestForAdmin, removeWorkerFromCleaningRequestForAdmin } from "../cleaning-request-assignment.service";

const worker = (id: string, type: "CREW" | "CONTRACTOR" = "CREW", isActive = true) => ({ id, firstName: id, lastName: "Worker", type, isActive });
function fixture(status: CleaningRequestStatus = CleaningRequestStatus.CONFIRMED, propertyType: "HOUSE" | "COMMERCIAL" = "HOUSE", initial: string[] = []) {
  const state = { id: "request-1", requestNumber: "CR-2030-0001", status, propertyType, assignments: initial.map((id) => ({ id: `assignment-${id}`, workerId: id, assignedAt: new Date("2030-01-01T12:00:00Z"), worker: worker(id) })) };
  const workers = new Map<string, ReturnType<typeof worker>>(); initial.forEach((id) => workers.set(id, worker(id))); workers.set("maria", worker("maria")); workers.set("rosa", worker("rosa")); workers.set("contractor", worker("contractor", "CONTRACTOR")); workers.set("inactive", worker("inactive", "CREW", false));
  const assignmentHistory: unknown[] = []; const statusHistory: unknown[] = [];
  const database = { $transaction: async (callback: (tx: any) => Promise<unknown>) => callback({ cleaningRequest: { findUnique: async () => state, updateMany: async ({ where }: any) => { if (state.status !== where.status) return { count: 0 }; state.status = "ASSIGNED"; if (where.status === "ASSIGNED") state.status = "CONFIRMED"; return { count: 1 }; } }, worker: { findUnique: async ({ where }: any) => workers.get(where.id) ?? null }, cleaningAssignment: { create: async ({ data }: any) => { const row = { id: `assignment-${data.workerId}`, workerId: data.workerId, assignedAt: data.assignedAt, worker: workers.get(data.workerId)! }; state.assignments.push(row); return row; }, deleteMany: async ({ where }: any) => { const before = state.assignments.length; state.assignments = state.assignments.filter((a) => a.id !== where.id); return { count: before - state.assignments.length }; }, findUnique: async () => null, findMany: async () => state.assignments }, cleaningRequestAssignmentHistory: { create: async ({ data }: any) => { assignmentHistory.push(data); return data; } }, cleaningRequestStatusHistory: { create: async ({ data }: any) => { statusHistory.push(data); return { id: `status-${statusHistory.length}`, ...data }; } } }) } as any;
  return { state, assignmentHistory, statusHistory, database };
}

describe("cleaning request assignment service", () => {
  it("performs first and additional assignments with one lifecycle transition", async () => { const f = fixture(); const first = await assignWorkerToCleaningRequestForAdmin("admin-1", { cleaningRequestId: "request-1", workerId: "maria" }, { database: f.database }); assert.equal(first.success, true); assert.equal(f.state.status, CleaningRequestStatus.ASSIGNED); const second = await assignWorkerToCleaningRequestForAdmin("admin-1", { cleaningRequestId: "request-1", workerId: "rosa" }, { database: f.database }); assert.equal(second.success, true); assert.equal(f.state.assignments.length, 2); assert.equal(f.statusHistory.length, 1); assert.equal(f.assignmentHistory.length, 2); });
  it("enforces residential, active, duplicate, status, and strict-input rules", async () => { assert.equal((await assignWorkerToCleaningRequestForAdmin("admin-1", { cleaningRequestId: "request-1", workerId: "contractor" }, { database: fixture().database }) as any).reason, "WORKER_NOT_ELIGIBLE"); assert.equal((await assignWorkerToCleaningRequestForAdmin("admin-1", { cleaningRequestId: "request-1", workerId: "inactive" }, { database: fixture().database }) as any).reason, "WORKER_INACTIVE"); const duplicate = fixture(CleaningRequestStatus.ASSIGNED, "HOUSE", ["maria"]); assert.equal((await assignWorkerToCleaningRequestForAdmin("admin-1", { cleaningRequestId: "request-1", workerId: "maria" }, { database: duplicate.database }) as any).reason, "WORKER_ALREADY_ASSIGNED"); assert.equal((await assignWorkerToCleaningRequestForAdmin("admin-1", { cleaningRequestId: "request-1", workerId: "maria", workerType: "CREW" }, { database: fixture().database }) as any).reason, "INVALID_INPUT"); assert.equal((await assignWorkerToCleaningRequestForAdmin("admin-1", { cleaningRequestId: "request-1", workerId: "maria" }, { database: fixture(CleaningRequestStatus.NEW).database }) as any).reason, "INVALID_REQUEST_STATUS"); });
  it("removes one worker without changing ASSIGNED and returns the last request to CONFIRMED", async () => { const f = fixture(CleaningRequestStatus.ASSIGNED, "HOUSE", ["maria", "rosa"]); const one = await removeWorkerFromCleaningRequestForAdmin("admin-1", { cleaningRequestId: "request-1", workerId: "maria", reason: "Worker unavailable" }, { database: f.database }); assert.equal(one.success, true); assert.equal(f.state.status, CleaningRequestStatus.ASSIGNED); assert.equal(f.state.assignments.length, 1); const last = await removeWorkerFromCleaningRequestForAdmin("admin-1", { cleaningRequestId: "request-1", workerId: "rosa", reason: "Replacement" }, { database: f.database }); assert.equal(last.success, true); assert.equal(f.state.status, CleaningRequestStatus.CONFIRMED); assert.equal(f.state.assignments.length, 0); assert.equal(f.statusHistory.length, 1); assert.equal(f.assignmentHistory.length, 2); });
  it("requires a non-whitespace removal reason and refuses missing assignments", async () => { const f = fixture(CleaningRequestStatus.ASSIGNED, "HOUSE", ["maria"]); assert.equal((await removeWorkerFromCleaningRequestForAdmin("admin-1", { cleaningRequestId: "request-1", workerId: "maria", reason: "   " }, { database: f.database }) as any).reason, "REMOVAL_REASON_REQUIRED"); assert.equal((await removeWorkerFromCleaningRequestForAdmin("admin-1", { cleaningRequestId: "request-1", workerId: "rosa", reason: "Correction" }, { database: f.database }) as any).reason, "ASSIGNMENT_NOT_FOUND"); });
});
