import assert from "node:assert/strict";
import test from "node:test";
import { CleaningRequestStatus } from "../../generated/prisma/client.js";
import { getCleaningRequestStatusHistory, transitionCleaningRequestStatusForAdmin } from "../cleaning-request-lifecycle.service.js";

type State = { id: string; requestNumber: string; status: CleaningRequestStatus; cancelledAt: Date | null; cancellationReason: string | null };
function database(initial: Partial<State> = {}, historyFailure = false) { let state: State = { id: "request-1", requestNumber: "JC-2026-0001", status: CleaningRequestStatus.NEW, cancelledAt: null, cancellationReason: null, ...initial }; const history: Array<{ id: string; fromStatus: CleaningRequestStatus; toStatus: CleaningRequestStatus; reason: string | null; createdAt: Date }> = []; const db = { state: () => state, history, async $transaction<T>(callback: (transaction: { cleaningRequest: { findUnique: (args: { where: { id: string } }) => Promise<{ id: string; requestNumber: string; status: CleaningRequestStatus } | null>; updateMany: (args: { where: { status: CleaningRequestStatus }; data: { status: CleaningRequestStatus; cancelledAt?: Date; cancellationReason?: string | null } }) => Promise<{ count: number }> }; cleaningRequestStatusHistory: { create: (args: { data: { fromStatus: CleaningRequestStatus; toStatus: CleaningRequestStatus; reason: string | null; createdAt: Date } }) => Promise<typeof history[number]> } }) => Promise<T>) { const before = { ...state }; const historyLength = history.length; try { return await callback({ cleaningRequest: { async findUnique(args) { return args.where.id === state.id ? { id: state.id, requestNumber: state.requestNumber, status: state.status } : null; }, async updateMany(args) { if (args.where.status !== state.status) return { count: 0 }; state = { ...state, status: args.data.status, cancelledAt: args.data.cancelledAt ?? state.cancelledAt, cancellationReason: args.data.cancellationReason ?? state.cancellationReason }; return { count: 1 }; } }, cleaningRequestStatusHistory: { async create(args) { if (historyFailure) throw new Error("history failed"); const row = { id: `history-${history.length + 1}`, fromStatus: args.data.fromStatus, toStatus: args.data.toStatus, reason: args.data.reason, createdAt: args.data.createdAt }; history.push(row); return row; } } }); } catch (error) { state = before; history.splice(historyLength); throw error; } }, cleaningRequestStatusHistory: { async findMany() { return history.map((row) => ({ ...row, changedByAdminUser: { id: "admin-1", name: "Admin", email: "admin@example.com" } })); } } }; return db; }

test("transitions atomically and attributes the authenticated admin", async () => { const db = database(); const result = await transitionCleaningRequestStatusForAdmin("admin-1", { cleaningRequestId: "request-1", toStatus: "REVIEWING" }, { database: db as never, now: new Date("2026-08-14T15:00:00Z") }); assert.equal(result.success, true); assert.equal(db.state().status, CleaningRequestStatus.REVIEWING); assert.deepEqual(db.history[0], { id: "history-1", fromStatus: "NEW", toStatus: "REVIEWING", reason: null, createdAt: new Date("2026-08-14T15:00:00Z") }); });
test("requires cancellation reasons and updates cancellation fields atomically", async () => { const db = database(); assert.deepEqual(await transitionCleaningRequestStatusForAdmin("admin-1", { cleaningRequestId: "request-1", toStatus: "CANCELLED", reason: "  " }, { database: db as never }), { success: false, reason: "CANCELLATION_REASON_REQUIRED" }); const result = await transitionCleaningRequestStatusForAdmin("admin-1", { cleaningRequestId: "request-1", toStatus: "CANCELLED", reason: " Outside service area " }, { database: db as never, now: new Date("2026-08-14T15:00:00Z") }); assert.equal(result.success, true); assert.equal(db.state().cancellationReason, "Outside service area"); assert.equal(db.state().cancelledAt?.toISOString(), "2026-08-14T15:00:00.000Z"); });
test("rejects invalid, strict, same-state, and unknown requests without mutation", async () => { const db = database(); const same = await transitionCleaningRequestStatusForAdmin("admin-1", { cleaningRequestId: "request-1", toStatus: "NEW" }, { database: db as never }); assert.equal(same.success ? "SUCCESS" : same.reason, "INVALID_TRANSITION"); const strict = await transitionCleaningRequestStatusForAdmin("admin-1", { cleaningRequestId: "request-1", toStatus: "CONFIRMED", fromStatus: "NEW" }, { database: db as never }); assert.equal(strict.success ? "SUCCESS" : strict.reason, "INVALID_INPUT"); const missing = database({ id: "different" }); const notFound = await transitionCleaningRequestStatusForAdmin("admin-1", { cleaningRequestId: "request-1", toStatus: "REVIEWING" }, { database: missing as never }); assert.equal(notFound.success ? "SUCCESS" : notFound.reason, "REQUEST_NOT_FOUND"); });
test("rolls back status when history creation fails", async () => { const db = database({}, true); const result = await transitionCleaningRequestStatusForAdmin("admin-1", { cleaningRequestId: "request-1", toStatus: "REVIEWING" }, { database: db as never }); assert.deepEqual(result, { success: false, reason: "INTERNAL_ERROR" }); assert.equal(db.state().status, CleaningRequestStatus.NEW); assert.equal(db.history.length, 0); });
test("returns a guarded status conflict and never creates misleading history", async () => { const db = database(); const result = await transitionCleaningRequestStatusForAdmin("admin-1", { cleaningRequestId: "request-1", toStatus: "REVIEWING" }, { database: { ...db, $transaction: async (callback: (transaction: never) => Promise<unknown>) => callback({ cleaningRequest: { async findUnique() { return { id: "request-1", requestNumber: "JC-2026-0001", status: CleaningRequestStatus.NEW }; }, async updateMany() { return { count: 0 }; } }, cleaningRequestStatusHistory: { async create() { throw new Error("should not run"); } } } as never) } as never }); assert.deepEqual(result, { success: false, reason: "STATUS_CONFLICT" }); assert.equal(db.history.length, 0); });
test("reads history oldest first without password fields", async () => { const db = database(); db.history.push({ id: "history-2", fromStatus: "REVIEWING", toStatus: "CONFIRMED", reason: null, createdAt: new Date("2026-08-15") }, { id: "history-1", fromStatus: "NEW", toStatus: "REVIEWING", reason: "Accepted", createdAt: new Date("2026-08-14") }); const result = await getCleaningRequestStatusHistory("request-1", { database: db as never }); assert.deepEqual(result.map((item) => item.id), ["history-2", "history-1"]); assert.equal("passwordHash" in (result[0] ?? {}), false); });
