import assert from "node:assert/strict";
import test from "node:test";
import { createCustomerProperty } from "../customer-property.service.js";

function database(customer: { id: string; isActive: boolean } | null) { const calls: unknown[] = []; return { calls, customer: { async findUnique() { return customer; } }, customerProperty: { async create(args: unknown) { calls.push(args); return { id: "property-1", customerId: "customer-1", isActive: true }; } } }; }
const valid = { propertyType: "OFFICE", addressLine1: "1 Main St", city: "Newark", state: "nj", postalCode: "07102", bedrooms: 3, bathrooms: 1.5 };
test("creates an active property and normalizes commercial bedrooms and blank bathrooms", async () => { const db = database({ id: "customer-1", isActive: true }); const result = await createCustomerProperty("customer-1", { ...valid, bathrooms: "   " }, { database: db as never }); assert.equal(result.status, "SUCCESS"); assert.equal((db.calls[0] as { data: { bedrooms: number | null; bathrooms: string | null; isActive: boolean } }).data.bedrooms, null); assert.equal((db.calls[0] as { data: { bedrooms: number | null; bathrooms: string | null; isActive: boolean } }).data.bathrooms, null); assert.equal((db.calls[0] as { data: { bedrooms: number | null; bathrooms: string | null; isActive: boolean } }).data.isActive, true); });
test("rejects unknown and inactive customers before mutation", async () => { assert.equal((await createCustomerProperty("missing", valid, { database: database(null) as never })).status, "CUSTOMER_NOT_FOUND"); assert.equal((await createCustomerProperty("customer-1", valid, { database: database({ id: "customer-1", isActive: false }) as never })).status, "CUSTOMER_INACTIVE"); });
test("validates saved property boundaries and strict fields", async () => { assert.equal((await createCustomerProperty("customer-1", { ...valid, state: "ZZ" }, { database: database({ id: "customer-1", isActive: true }) as never })).status, "INVALID_INPUT"); assert.equal((await createCustomerProperty("customer-1", { ...valid, bathrooms: 1.25 }, { database: database({ id: "customer-1", isActive: true }) as never })).status, "INVALID_INPUT"); assert.equal((await createCustomerProperty("customer-1", { ...valid, privileged: false }, { database: database({ id: "customer-1", isActive: true }) as never })).status, "INVALID_INPUT"); });
